# Generated by Django 3.1.7 on 2021-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Задача')),
                ('text', models.TextField(blank=True, max_length=3000, verbose_name='Описание')),
                ('check', models.CharField(blank=True, default='new', max_length=100, verbose_name='Статус')),
                ('date', models.DateField(default='', verbose_name='Дата выполнения')),
            ],
        ),
    ]
